name: Build

on: 
  workflow_dispatch:
    inputs:
      ver_num:
        description: 'Version Number'
        type: string
        required: true
      prerelease:
        description: 'Is this build is pre-release?'
        required: false
        type: boolean



permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}


    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm audit fix --force && npm ci
        shell: bash

      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash
      
      - uses: actions/upload-artifact@v4
        name: Action-Upload
        with:
          name: ${{ runner.os }}-release
          path: |
            dist/latest*.yml
            dist/GlowLauncher-setup-${{ inputs.ver_num }}*

  release:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:

      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2


      - uses: actions/download-artifact@v4
        name: Action-Download
        with:
          path: dist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.ver_num }}
          name: GlowLauncher - ${{ inputs.ver_num }}
          body: |
            ### ▼ご使用のOSのインストーラーをダウンロードしてください。
            [Windows](https://github.com/${{ github.repository }}/releases/download/${{ inputs.ver_num }}/GlowLauncher-setup-${{ inputs.ver_num }}.exe)
            [Linux](https://github.com/${{ github.repository }}/releases/download/${{ inputs.ver_num }}/GlowLauncher-setup-${{ inputs.ver_num }}.Appimage)

            ### ビルド情報
            ${{ inputs.ver_num }} by ${{ github.actor }}
          draft: false
          prerelease: ${{ inputs.prerelease }}
          files: |
            dist/**/latest*.yml
            dist/**/GlowLauncher-setup-${{ inputs.ver_num }}*